### PR TITLE
testing Update jobs.md

### PR DESCRIPTION
**Pull request by LucaFumis**

### CODE REVIEW

**Comment by opentargets-fern** [comment]
Deploy preview ready!

Built with commit e0a8c7844c21685fd4e77763b1bef37eabcda37e

https://deploy-preview-5--journalist-crab-36716.netlify.com

**Comment by elipapa** [comment]
@LucaFumis this seem to have worked nicely?

**Comment by LucaFumis** [comment]
Yes @elipapa, it worked like a charm!
Actually, we were thinking of:
1. keeping a branch+PR open at all times, for @HollyFoster to edit/preview changes whenever she needs
2. merge changes into master when she's happy with the updates

Would that work or do you see any pitfalls?

**Comment by elipapa** [comment]
whatever works. 
only pitfall is potentially that this `dev` branch with time could get out of sync with other changes in master..
is it annoying to open a branch + create a PR every change?

**Comment by LucaFumis** [comment]
Thanks Eliseo, will keep that in mind.
Today we looked at branch/PR for editing/preview, but without going into the details of making one.
I see that GitHub allows to create a branch directly from the UI, so that's probably straightforward - I'll see with Holly what she's more comfortable with...

**Pull request merged**
